# Generated by Django 3.1.7 on 2021-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demps_one_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Last_Name',
            new_name='last_mame',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Confirm_Password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='exit', max_length=45),
            preserve_default=False,
        ),
    ]
